/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafka.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserList extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5281563269210173813L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserList\",\"namespace\":\"com.kafka.schema\",\"fields\":[{\"name\":\"Users\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"UserExample\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"gender\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"},{\"name\":\"age\",\"type\":\"int\",\"default\":\"\"},{\"name\":\"group\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserList> ENCODER =
      new BinaryMessageEncoder<UserList>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserList> DECODER =
      new BinaryMessageDecoder<UserList>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<UserList> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<UserList> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserList>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this UserList to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a UserList from a ByteBuffer. */
  public static UserList fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<com.kafka.schema.UserExample> Users;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserList() {}

  /**
   * All-args constructor.
   * @param Users The new value for Users
   */
  public UserList(java.util.List<com.kafka.schema.UserExample> Users) {
    this.Users = Users;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Users;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Users = (java.util.List<com.kafka.schema.UserExample>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Users' field.
   * @return The value of the 'Users' field.
   */
  public java.util.List<com.kafka.schema.UserExample> getUsers() {
    return Users;
  }

  /**
   * Sets the value of the 'Users' field.
   * @param value the value to set.
   */
  public void setUsers(java.util.List<com.kafka.schema.UserExample> value) {
    this.Users = value;
  }

  /**
   * Creates a new UserList RecordBuilder.
   * @return A new UserList RecordBuilder
   */
  public static com.kafka.schema.UserList.Builder newBuilder() {
    return new com.kafka.schema.UserList.Builder();
  }

  /**
   * Creates a new UserList RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserList RecordBuilder
   */
  public static com.kafka.schema.UserList.Builder newBuilder(com.kafka.schema.UserList.Builder other) {
    return new com.kafka.schema.UserList.Builder(other);
  }

  /**
   * Creates a new UserList RecordBuilder by copying an existing UserList instance.
   * @param other The existing instance to copy.
   * @return A new UserList RecordBuilder
   */
  public static com.kafka.schema.UserList.Builder newBuilder(com.kafka.schema.UserList other) {
    return new com.kafka.schema.UserList.Builder(other);
  }

  /**
   * RecordBuilder for UserList instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserList>
    implements org.apache.avro.data.RecordBuilder<UserList> {

    private java.util.List<com.kafka.schema.UserExample> Users;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafka.schema.UserList.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Users)) {
        this.Users = data().deepCopy(fields()[0].schema(), other.Users);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing UserList instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafka.schema.UserList other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Users)) {
        this.Users = data().deepCopy(fields()[0].schema(), other.Users);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'Users' field.
      * @return The value.
      */
    public java.util.List<com.kafka.schema.UserExample> getUsers() {
      return Users;
    }

    /**
      * Sets the value of the 'Users' field.
      * @param value The value of 'Users'.
      * @return This builder.
      */
    public com.kafka.schema.UserList.Builder setUsers(java.util.List<com.kafka.schema.UserExample> value) {
      validate(fields()[0], value);
      this.Users = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Users' field has been set.
      * @return True if the 'Users' field has been set, false otherwise.
      */
    public boolean hasUsers() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Users' field.
      * @return This builder.
      */
    public com.kafka.schema.UserList.Builder clearUsers() {
      Users = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserList build() {
      try {
        UserList record = new UserList();
        record.Users = fieldSetFlags()[0] ? this.Users : (java.util.List<com.kafka.schema.UserExample>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserList>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserList>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserList>
    READER$ = (org.apache.avro.io.DatumReader<UserList>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
