/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafka.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserGroup extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4217877866583198620L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserGroup\",\"namespace\":\"com.kafka.schema\",\"fields\":[{\"name\":\"group\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserGroup> ENCODER =
      new BinaryMessageEncoder<UserGroup>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserGroup> DECODER =
      new BinaryMessageDecoder<UserGroup>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<UserGroup> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<UserGroup> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserGroup>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this UserGroup to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a UserGroup from a ByteBuffer. */
  public static UserGroup fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String group;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserGroup() {}

  /**
   * All-args constructor.
   * @param group The new value for group
   */
  public UserGroup(java.lang.String group) {
    this.group = group;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return group;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: group = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'group' field.
   * @return The value of the 'group' field.
   */
  public java.lang.String getGroup() {
    return group;
  }

  /**
   * Sets the value of the 'group' field.
   * @param value the value to set.
   */
  public void setGroup(java.lang.String value) {
    this.group = value;
  }

  /**
   * Creates a new UserGroup RecordBuilder.
   * @return A new UserGroup RecordBuilder
   */
  public static com.kafka.schema.UserGroup.Builder newBuilder() {
    return new com.kafka.schema.UserGroup.Builder();
  }

  /**
   * Creates a new UserGroup RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserGroup RecordBuilder
   */
  public static com.kafka.schema.UserGroup.Builder newBuilder(com.kafka.schema.UserGroup.Builder other) {
    return new com.kafka.schema.UserGroup.Builder(other);
  }

  /**
   * Creates a new UserGroup RecordBuilder by copying an existing UserGroup instance.
   * @param other The existing instance to copy.
   * @return A new UserGroup RecordBuilder
   */
  public static com.kafka.schema.UserGroup.Builder newBuilder(com.kafka.schema.UserGroup other) {
    return new com.kafka.schema.UserGroup.Builder(other);
  }

  /**
   * RecordBuilder for UserGroup instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserGroup>
    implements org.apache.avro.data.RecordBuilder<UserGroup> {

    private java.lang.String group;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafka.schema.UserGroup.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.group)) {
        this.group = data().deepCopy(fields()[0].schema(), other.group);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing UserGroup instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafka.schema.UserGroup other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.group)) {
        this.group = data().deepCopy(fields()[0].schema(), other.group);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'group' field.
      * @return The value.
      */
    public java.lang.String getGroup() {
      return group;
    }

    /**
      * Sets the value of the 'group' field.
      * @param value The value of 'group'.
      * @return This builder.
      */
    public com.kafka.schema.UserGroup.Builder setGroup(java.lang.String value) {
      validate(fields()[0], value);
      this.group = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'group' field has been set.
      * @return True if the 'group' field has been set, false otherwise.
      */
    public boolean hasGroup() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'group' field.
      * @return This builder.
      */
    public com.kafka.schema.UserGroup.Builder clearGroup() {
      group = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserGroup build() {
      try {
        UserGroup record = new UserGroup();
        record.group = fieldSetFlags()[0] ? this.group : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserGroup>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserGroup>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserGroup>
    READER$ = (org.apache.avro.io.DatumReader<UserGroup>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
